import Footer from '../../components/layout/footer'
import Header from '../../components/layout/header'  
import RecoilRootWrapper from '../../wrappers/RecoilRootWrapper'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
          <title>Flip Dot</title>
      </head>
      
      <body className={``}
        style={{
          backgroundColor : 'black',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'start',
          height: '100vh',
        }}
      >
          <Header />
          <div className={``} style={{minHeight : '1000px'}}>
            <RecoilRootWrapper>
                {children}
            </RecoilRootWrapper>
          </div>
          <Footer />
      </body>
    </html>
  )
}
